// API-1 
                 //Secnario-1
GET  http://localhost:3000/todos/?status=TO%20DO 
###

                 //Secnario-2
GET  http://localhost:3000/todos/?priority=HIGH 
###

                 //Secnario-3
GET  http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS 
###

                 //Secnario-4
GET  http://localhost:3000/todos/?search_q=Buy 
###

                 //Secnario-5
GET  http://localhost:3000/todos/?category=WORK&status=DONE 
###

                 //Secnario-6
GET  http://localhost:3000/todos/?category=HOME 
###

                 //Secnario-7
GET  http://localhost:3000/todos/?category=LEARNING&priority=HIGH 
###


// API-2 request to get the specific todo based on id

GET http://localhost:3000/todos/2/
###


// API-3 request to get the spefic todo based on the date
GET http://localhost:3000/agenda/?date=2021-12-12  


###

//API-4 create todo details 
PUT   http://localhost:3000/todos/ 
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
### 

//API-5 update todo details scenarios 

//Scenario-1 upadate status
PUT   http://localhost:3000/todos/6/ 
Content-Type: application/json

{
  "status": "DONE"
}

###
 
//Scenario-2 upadate priority
PUT   http://localhost:3000/todos/6/ 
Content-Type: application/json

{
  "priority": "HIGH"
}
###

//Scenario-3 upadate todo
PUT   http://localhost:3000/todos/6/ 
Content-Type: application/json

{
  "todo": "Clean the garden"
}
###

//Scenario-4 upadate category
PUT   http://localhost:3000/todos/6/ 
Content-Type: application/json

{
  "category": "LEARNING"
}
###

//Scenario-5 upadate due date 
PUT   http://localhost:3000/todos/6/ 
Content-Type: application/json

{
  "dueDate": "2021-01-12"
}
###

//API-6 Delete the specific todo based on id
DELETE http://localhost:3000/todos/6/ 
###